### ISSUE TITLE
lazy_static? multi threading?

### ISSUE THREAD

**Issue by fivethousand** [emoon/dynamic_reload#10]
Is there a suggested way to use this together with lazy_static and possibly also multi threading...? 

I tried
```
lazy_static! {
    pub static ref PLUGINS: Plugins = create_plugins();
}
```

but lazy_static does not work with Rc<>, and changing Rc<> to Arc<> results in the following error:
```
the trait `std::marker::Sync` is not implemented for `*mut std::os::raw::c_void`
   = note: `*mut std::os::raw::c_void` cannot be shared between threads safely
```

Do you have any ideas? The error suggests that we shouldn't use it with multi threading anyway...

**Comment by emoon** [comment]
Hi,

I haven't looked into this no. When you resolve a symbol from the library it should be possible to call it on other threads as "extracting" the pointer is an unsafe operation and calling the code itself is unsafe as well.

I can try to take a look at this but it won't happen for a while because I'm currently busy with other stuff. Sorry about that.

**Comment by fivethousand** [comment]
Thanks.
Actually the issue already exists in rust_libloading, so I'll report it upstream.

**Comment by fivethousand** [comment]
This was already fixed in rust_libloading. Please update the version to 0.3.

Thanks!

**Comment by emoon** [comment]
Alright. I will try to get around to do this later today.

**Comment by emoon** [comment]
Hi. I tried update to 0.3 of rust_libloading and I'm running into some issues in the tests. I'm sorry but simply don't have time to investigate why it doesn't work right now.

**Comment by fivethousand** [comment]
No worries, I totally understand your situation.
Fortunately only one path was wrong; here's what you have to change to fix the failing tests:

change src/lib.rs:520 to
`let lib_path = exe_path.parent().unwrap().parent().unwrap();`

And, of course, change Cargo.toml:16 to
`libloading = "0.3.0"`

Then,
`test result: ok. 22 passed; 0 failed; 0 ignored; 0 measured`

I could have submitted a PR, but this is really just a one-liner ;-)

Thanks for taking your time.

**Comment by emoon** [comment]
Ah cool. I can get that sorted out then :) I will try to release a new updated version later today. Thanks for looking into the issue :)

**Comment by emoon** [comment]
I have release version `0.2.1` now which includes updated `rust_libloading` to 0.3.0

**Comment by fivethousand** [comment]
Thanks.

Unfortunately, I had to fork anyway: Multi threading requires Arc<> instead of Rc<>.
You shouldn't incorporate this as a default, of course... Maybe there is a clever way to support both.

**Comment by emoon** [comment]
Ah I see. Yeah I will have to think about that one.

**Comment by emoon** [comment]
@fivethousand just FYI I have updated 0.3.0 of this crate to use `Arc<>` instead of 'Rc<>'
