### ISSUE TITLE
Configurable debounce time

### ISSUE THREAD

**Issue by Boscop** [emoon/dynamic_reload#19]
Thanks for making this crate :)
I plan to use it for live coding, and I noticed it uses a 2s delay (`notify::watcher(tx, Duration::from_secs(2))`), which is too long for my use case, because the recompilation of the dll also adds wait time.
Could you please make this delay configurable? :)

**Comment by emoon** [comment]
Thanks! I currently don't have much time to work on this crate anymore, but I would be happy to accept a PR for this feature (with the default value being 2)

**Comment by Boscop** [comment]
@emoon Ok. Btw, is the `WRITE` even that `notify` generates being sent for every write call to the dll file, even before it's closed? Or is it only being sent once when the dll file has been closed after being opened for writing?

**Comment by emoon** [comment]
Best is to look at the documentation for https://github.com/notify-rs/notify (in general this may differ a bit between platforms also)

**Comment by emoon** [comment]
Fixed in https://github.com/emoon/dynamic_reload/pull/24
