### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Boscop** [emoon/dynamic_reload#20]
1:
[Here](https://docs.rs/dynamic_reload/0.4.0/dynamic_reload/struct.DynamicReload.html#method.add_library) it says:
> 1. Current directory
> 2. In the search paths (relative to current directory)
> 3. Current directory of the executable
> 4. Search backwards from executable if Backwards has been set DynamicReload::new

What's the difference between 1 and 3?

---

2:
When wanting to auto-reload multiple dlls, is it recommended to use separate instances of `DynamicReload` or should only one instance be used? 
I'm asking because the crate example uses a `Vec` for the list of plugins, but conceptually it would be easier to use separate instances, so that there is no way to accidentally use the wrong `Plugin` trait object with the wrong `Lib`:
```rust
struct PluginManager {
	plugin: Box<dyn Plugin>,
	lib: Arc<Lib>,
}
```
Also so that individual plugins can be unloaded or stopped from being auto-reloaded.
(Since `DynamicReload` has no `remove_library` method.)

---

3:
Is it safe to move the `lib` (of type `Lib`) after this?
```rust
		let plugin = unsafe {
			let constructor: Symbol<PluginCreate> = lib.get(b"plugin_create\0").expect("plugin_create");
			let boxed_raw = constructor();
			Box::from_raw(boxed_raw)
		};
```
Or would moving `lib` invalidate the references into the dll (the trait object vtable)?
Is it correct that on all platforms this only moves the handle to the dll, and thus doesn't invalidate references into it?

---

4:
Have you seen this crate? It allows ensuring that no references to the dll outlive it:
https://docs.rs/sharedlib/7.0.0/sharedlib/#choosing-your-guarantees
It could make sense to use it in this crate.

---

5:
In the example you're using `extern "C"` for getting the function pointer:
https://github.com/emoon/dynamic_reload/blob/15365627b8e549d82016ad8adb2bf53223f869ca/examples/example.rs#L70
But it's not declared with `extern "C"`:
https://github.com/emoon/dynamic_reload/blob/15365627b8e549d82016ad8adb2bf53223f869ca/src/test_shared.rs#L3
For this example it makes no difference but with my DLL entry point returning a `Plugin` trait object (`type PluginCreate = extern "C" fn() -> *mut dyn Plugin;`) it causes access violation, so it would make sense to also use the same calling convention for export and import in the example.
Btw, why are you [using `dylib`](https://github.com/emoon/dynamic_reload/blob/15365627b8e549d82016ad8adb2bf53223f869ca/build.rs#L21) instead of `cdylib`. I'm using `cdylib` and it results in a smaller dll because unused symbols are removed etc.
Does `dylib` give more ABI stability guarantees?

**Comment by emoon** [comment]
1:   Say that you are standing in directory `foo` and then you run your executable such as `bar/exe` that means that the current directory is still `foo` but the exe is placed in `foo/bar/exe` thus the exe path and the current directory isn't the same

2. The intention is to use one instance.

3: This should be safe, but of course I may have missed something.

4: No, `dynamic_reload` was made before that crate.

5: It should likely be extern "C" here indeed yes, in this case it will always work as the signature is quite simple but in other cases it may perhaps not (it all depends on the ABI really, but having it as extern "C" is likely a good idea)

**Comment by Boscop** [comment]
Thanks! 

2. Would anything go wrong when using multiple instances (one per dll)?

**Comment by emoon** [comment]
I think multiple instances should work, that being said I have never tried it.
