### ISSUE TITLE
Upgrade to notify-rs 5.0.0 and the new debouncing mechanism

### ISSUE THREAD

**Issue by Boscop** [emoon/dynamic_reload#28]
It seems notify-rs 5.0.0 changed the debouncing mechanism. Now it's in a separate crate:
https://crates.io/crates/notify-debouncer-mini

Maybe it would fix this debounce issue: https://github.com/emoon/dynamic_reload/issues/27

**Comment by emoon** [comment]
Looking at switching over to 5.1 and it's kinda annoying as the `Debouncer` has been removed. The mini crate doesn't really fit with with what `dynamic_reload` does so I will have to investigate a bit more.

**Comment by emoon** [comment]
Actually... it might not be that bad. I will take a look at it during the weekend.

**Comment by emoon** [comment]
Work has been done and passes the tests on Linux. Please give this a test now.

**Comment by 0xpr03** [comment]
There is also debouncer-full, just so you know.

**Comment by emoon** [comment]
Thanks.

I have updated the code to using the debouncer-mini and it seems to work fine so I will close this issue now.
